version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-01-01 to 2020-12-01 by month" 
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  reformat_appointment_data:
    run: python:latest python analysis/reformat_appointment_data.py
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        reformatted: output/input_long*.csv

  calculate_lead_times:
    run: python:latest python analysis/calculate_lead_times.py
    needs: [reformat_appointment_data]
    outputs:
      highly_sensitive:
        calculated: output/input_processed*.csv

  summarise_lead_times:
    run: python:latest python analysis/summarise_lead_times.py
    needs: [calculate_lead_times]
    outputs:
      highly_sensitive:
        summarised: output/summary*.csv
