version: '3.0'

expectations:
  population_size: 5000

actions:

  generate_dataset:
    run: >
      databuilder:v0
        generate-dataset
        analysis/dataset_definition.py
        --output output/dataset_wide.csv
    outputs:
      highly_sensitive:
        dataset: output/dataset_wide.csv

  reshape_dataset:
    run: >
      python:latest
        python
        -m analysis.reshape_dataset
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        dataset: output/dataset_long.csv

  generate_measure:
    run: >
      python:latest
        python
        -m analysis.generate_measure
    needs: [reshape_dataset]
    outputs:
      moderately_sensitive:
        measure: output/measure_median_lead_time_in_days_by_nunique_patient_id.csv

  generate_deciles_charts:
    run: >
      deciles-charts:v0.0.33
        --input-files output/measure_*.csv 
        --output-dir output
    config:
      show_outer_percentiles: true
    needs: [generate_measure]
    outputs:
      moderately_sensitive:
        deciles_charts: output/deciles_chart_*.png
        deciles_tables: output/deciles_table_*.csv
